### PR TITLE
 Fix testrunner

### LINKED ISSUE #56: Current testsuite is unable to pass
A recent PR has showed that the testsuite is unable to run at all after the changes made with exercism v2.

This is related to the "journey" script I wrote a while back.

Idris should do it like the other tracks and revert to a simple runner that just runs all exercises in alphabetical (or any other) order.

### PR DESCRIPTION
**Pull request by NobbZ**
This PR is meant to make tests succeed on travis again.

FIX #56

### CODE REVIEW

**Comment by NobbZ** [comment]
Got this working for now.

Shall I do some more clean up in the scripts or shall I address those in another PR?

Also shall I update idris to the most current one or even set up a build matrix that checks with the most recent versions (I'd suggest 1.2 and 1.3)? And if so shall I tackle in this PR or open a new one?

Due to some major time constraints I weren't able to address anything else in the next week and therefore suggest to take this PR as is.

Then I can take a look at the other issues in a week or two, especially migrating to specdris (#43).

**Comment by yurrriq** [comment]
Awesome! I'd say group PRs however you like. It seems it would make sense to update Idris and the scripts here, but separate PRs would be fine too.

**Comment by NobbZ** [comment]
Then I'd suggest to merge this as soon as possible, as it would affect other PRs as well.

I had to learn though, that updating idris won't be that easy, it seems as if after 1.0 nothing is available on stackage anymore.

**Comment by yurrriq** [comment]
Thanks for this.

**Pull request merged**
