### PR TITLE
Introduce specdris and elba

### LINKED ISSUE #20: Failing tests are not expressive
I am trying to do `leap` and implemented it as ``leap y = isLeap year = (y `mod` 4) == 0`` as a first step. running the tests result in the following output:

```plain
% idris --testpkg Leap.ipkg
Entering directory `./src'
Type checking ./Test/Leap.idr
Type checking /tmp/idris1315634022635723058.idr
Test Passed
Test Passed
Test Failed
Test Passed
Leaving directory `./src'
```

It would be nice if a failing test could give us some more information about what kind of test it was. This way I have to try to read the testfiles, figure out which test is actually the third, hoping that execution order was not randomized, and then I have to understand the test.

### LINKED ISSUE #43: Consider Specdris
Since [idris-testing](https://github.com/jfdm/idris-testing) is archived, consider using [Specdris](https://github.com/pheymann/specdris).

### LINKED ISSUE #54: Remove obsolete version tracking assertions in exercises
Some tracks have added assertions to the exercise test suites that ensure that the solution has a hard-coded version in it.
In the old version of the site, this was useful, as it let commenters see what version of the test suite the code had been written against, and they wouldn't accidentally tell people that their code was wrong, when really the world had just moved on since it was submitted.

If this track does not have any assertions that track versions in the exercise tests, please close this issue.

If this track _does_ have this bookkeeping code, then please remove it from all the exercises.

See https://github.com/exercism/exercism/issues/4266 for the full explanation of this change.

### PR DESCRIPTION
**Pull request by NobbZ**
FIX #54 (remove version tracking tests)
FIX #43 (consider specdris)
FIX #20 (messages printed on failing tests are not useful)

### CODE REVIEW

**Comment by NobbZ** [comment]
This is a first draft, that is made to demonstrate on the example of hello-world how specdris would look like.

I'm not yet fixed on elba, but it seems to be the easiest.

If we decide on keeping it, I'll also add some words to the installation instructions.

**Comment by NobbZ** [comment]
PS: Of course all tests other than `hello-world` fail. I'll migrate them during the next couple of days.

**Comment by NobbZ** [comment]
Before merging, please let me know if we want to keep the `elba` approach or if we should prefer a global installation of `specdris` instead.

After that I'll change documentation accordingly. Also if we do not want to use `elba` I have to change the project structure again to rely on `ipkg` instead and a `Makefile` as it was before.

**Comment by yurrriq** [comment]
Thanks for doing this. At a glance, it looks good to me.

**Comment by NobbZ** [comment]
Okay, I'll see if I can update the documentation throughout this week.

I probably have to juggle a lot with my office job and family.

Especially in my office job, we are struck by the "christmas effect".(*)

(*) A yearly even taking place around may that is of high importance for our customers. This event though is ignored throughout the year, and about march we get orders, which we have to fulfill within 4 weeks, that there can be a testphase of another 4 weeks before the systems go live for 4 weeks during the event… Its the same pattern every year…

**Comment by thosgood** [comment]
will this get merged? it seems like Specdris is a pretty good way to go

**Comment by NobbZ** [comment]
Sorry, I totally forgot about this one. I should be able to schedule an hour or two to revise documentation in the next week.

**Pull request closed without merging**
