### PR TITLE
Update Travis build to use configlet subcommand

### PR DESCRIPTION
**Pull request by kytrinyx**
The configlet command changed a while back. I thought I had updated all the tracks to the new version of the command, but I appear to have missed this one.

### CODE REVIEW

**Comment by kytrinyx** [comment]
This fixed the `configlet lint` failure, but there's a second failure for the `accumulate` exercise. It looks like the journey test can't find the implementation files:

```
++ls '/home/travis/build/exercism/idris/build/exercism/idris/accumulate/src/*.idr'
ls: cannot access /home/travis/build/exercism/idris/build/exercism/idris/accumulate/src/*.idr: No such file or directory
```

**Comment by kytrinyx** [comment]
It looks like a problem due to the filesystem being case sensitive on Travis. I'll submit a separate PR with a fix for that.

**Comment by kytrinyx** [comment]
I'm building a branch that contains both this PR and #42 (https://travis-ci.org/exercism/idris/builds/329333269).

**Comment by kytrinyx** [comment]
Well. That didn't actually work. I'll take another look at it in a bit.

**Comment by kytrinyx** [comment]
Ah, I see what's going on here.

The journey test assumes that there's an idr file in the src directory, but since the Example doesn't get fetched, and there's no `Accumulate.idr` file, the command fails.

I'm going to add an empty `Accumulate.idr` file—I'm not certain that this is the correct approach, but it will at least give us something to discuss.

**Comment by kytrinyx** [comment]
The branch that combines #41 and #42 is now passing 
https://travis-ci.org/exercism/idris/builds/329514216

**Comment by yurrriq** [comment]
I missed this and committed the same change just now.. Closing.

**Pull request closed without merging**
