### PR TITLE
Add resistor-color

### PR DESCRIPTION
**Pull request by keiravillekode**

### CODE REVIEW

**Comment by keiravillekode** [comment]
We could make the return type  `Maybe Int`  .  The canonical tests for this exercise don't have an error cases as it supposed to be an easy exercise.    So I haven't made that change.

**Review by isberg — APPROVED** [review]
A return type of Maybe Int seems better, but I wont mind that being a separate PR.

**Comment by keiravillekode** [comment]
Done.  This will boost the difficulty of resistor-color-duo / resistor-color-trio, and I like to keep the resistor-color exercises together, so I have boosted the resistor-color difficulty.

**Review by isberg — APPROVED** [review]
A possible alternative would be to have a function `Color -> Fin 10` instead of `String -> Maybe (Fin 10)`. Not sure which makes more sense fur this exercise.

**Pull request merged**
