### PR TITLE
Accumulate: allow more generic implementations

### LINKED ISSUE #45: Accept a more generic Accumulate
I think this solution should be accepted by the tests: http://exercism.io/submissions/bec1bec2b70847588ca3dad4b52cc3b6

This could be accomplished by changing the type of `assertEq` to be more specific. Do you think it's a good idea?

### PR DESCRIPTION
**Pull request by ktosiek**
This fixes #45 by using a more specific `assertEq`.

### CODE REVIEW

**Comment by yurrriq** [comment]
I still don't like this... What do you think about something like the following instead?

```diff
11c11
< testEmptyListDoesNothing = assertEq "empty list does nothing" (accumulate (\x => x) []) []
---
> testEmptyListDoesNothing = assertEq "empty list does nothing" (accumulate (\x => x) (the (List Int) []))  []
26c26
< testDecrementFunctionAddsOneToAllInput = assertEq "decrement function subtracts 1 from input" (accumulate (\x => x - 1) [1,2,3]) [0,1,2]
---
> testDecrementFunctionAddsOneToAllInput = assertEq "decrement function subtracts 1 from input" (accumulate (\x => x - 1) [1,2,3]) (the (List Int) [0,1,2])
```

**Comment by yurrriq** [comment]
`Example.idr` could then be generic like [the solution](http://exercism.io/submissions/bec1bec2b70847588ca3dad4b52cc3b6) from #45

**Comment by ktosiek** [comment]
I didn't know about the `the`, I've moved to the approach you proposed.

**Comment by yurrriq** [comment]
LGMT thanks

**Pull request merged**
