### PR TITLE
Add 'math' topic to relevant exercises in track config

### PR DESCRIPTION
**Pull request by kytrinyx**
The new site lets people filter optional exercises by topic, and this
makes it easy for people to skip past them.

This is important since the math-y exercises are not key to learning
the language, and a lot of people find them intimidating and demotivating.

This updates any 'mathematics' topics to be 'math' since it's shorter
and won't get cropped in the UI.

It also removes the math topics for any exercises that are not in the
canonical math-y list.

exercism/exercism.io#4110

### CODE REVIEW

**Comment by kytrinyx** [comment]
@yurrriq I don't know if you want something to signal integer division for the `leap` exercise here. I've removed `arithmetic` since we have a canonical list of exercises that are marked `math` (though none in this track).

The build failed, but I think it just stalled, so I've retriggered it to see if that helps.

**Comment by kytrinyx** [comment]
Hm, actually one of the builds stalled, the other failed. I don't think it's related to this change though.

**Comment by NobbZ** [comment]
You are right, it's unrelated. Tests are failing because I set up a journey for this track.

Later today I'll see if I can switch back to a regular testdiscovery and make a PR for that.

**Comment by NobbZ** [comment]
Hello @kytrinyx, could you try to rebase or backmerge master? Such that you have latest test runners available, then tests should pass.

Alternatively, you should be able to just merge in the change, as no one else seems to feel responsible for this.

**Comment by yurrriq** [comment]
Somehow, I missed this. Sorry. This looks fine to merge, so I think we should, perhaps after #58.

**Comment by kytrinyx** [comment]
Let's get #58 in, and then I'll rebase and we can see the state of things.

**Pull request closed without merging**
